syntax = "proto3";

option csharp_namespace = "TrackYourTripGRPCApi.Protos";

package auth;

service Auth{
  rpc Register (RegisterRequest) returns (RegisterResponse);
  rpc Login (LoginRequest) returns (LoginResponse);
}

message RegisterRequest {
  string email = 1;
  string password = 2;
  string name = 3;
  string groupName = 4;
  bool isNewGroup = 5;
}

message RegisterResponse {
  bool isSuccess = 1;
  int32 statusCode = 2;
  string errorMessage = 3;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  bool isSuccess = 1;
  string token = 2;
  int32 statusCode = 3;
  string errorMessage = 4;
}
