syntax = "proto3";

option csharp_namespace = "TrackYourTripGRPCApi.Protos";

package member;

service Member {
  rpc GetMember (GetMemberRequest) returns (GetMemberResponse);
  rpc GetAllMembersByGroup (GetAllMembersByGroupRequest) returns (GetAllMembersByGroupResponse);
  rpc GetAllMembersByTrip (GetAllMembersByTripRequest) returns (GetAllMembersByTripResponse);
  rpc CreateMembers (CreateMembersRequest) returns (CreateMembersResponse);
  rpc DeleteMembers (DeleteMembersRequest) returns (DeleteMembersResponse);
}

message MemberDetail {
  int32 id = 1;
  string name = 2;
  string email = 3;
  int32 tripId = 4;
  double totalTripExpense = 5;
}

message GetMemberRequest {
  int32 id = 1;
}

message GetMemberResponse {
  MemberDetail member = 1;
}

message GetAllMembersByGroupRequest {
  int32 groupId = 1;
}

message GetAllMembersByGroupResponse {
  repeated MemberDetail members = 1;
}

message GetAllMembersByTripRequest {
  int32 tripId = 1;
}

message GetAllMembersByTripResponse {
  repeated MemberDetail members = 1;
}

message CreateMembersRequest {
  repeated MemberDetail members = 1;
}

message CreateMembersResponse {
  bool success = 1;
}

message DeleteMembersRequest {
  repeated int32 memberIds = 1;
}

message DeleteMembersResponse {
  bool success = 1;
}

